name: Lint Code with flake8

# Trigger when someone pushes to dev branch
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install flake8
      - name: Install flake8
        run: pip install flake8

      # 4. Run lint
      - name: Run flake8
        run: flake8 .
