name: Run Unit Tests

# Trigger when code is pushed to test branch
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      # 4. Run unit tests
      - name: Run pytest
        run: pytest
